<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'Simple_History\Vendor\Jfcherng\Utility\MbString' => $strauss_src . '/jfcherng/php-mb-string/src/MbString.php',
   'Simple_History\Vendor\Jfcherng\Diff\SequenceMatcher' => $strauss_src . '/jfcherng/php-sequence-matcher/src/SequenceMatcher.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\RendererInterface' => $strauss_src . '/jfcherng/php-diff/src/Renderer/RendererInterface.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\AbstractRenderer' => $strauss_src . '/jfcherng/php-diff/src/Renderer/AbstractRenderer.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\LineRendererInterface' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/LineRendererInterface.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\Char' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/Char.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\None' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/None.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\Line' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/Line.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\Word' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/Word.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\LineRenderer\AbstractLineRenderer' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/LineRenderer/AbstractLineRenderer.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\SideBySide' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/SideBySide.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\Json' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/Json.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\Combined' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/Combined.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\AbstractHtml' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/AbstractHtml.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\JsonHtml' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/JsonHtml.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Html\Inline' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Html/Inline.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\RendererConstant' => $strauss_src . '/jfcherng/php-diff/src/Renderer/RendererConstant.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Text\AbstractText' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Text/AbstractText.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Text\Context' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Text/Context.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Text\Unified' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Text/Unified.php',
   'Simple_History\Vendor\Jfcherng\Diff\Renderer\Text\JsonText' => $strauss_src . '/jfcherng/php-diff/src/Renderer/Text/JsonText.php',
   'Simple_History\Vendor\Jfcherng\Diff\DiffHelper' => $strauss_src . '/jfcherng/php-diff/src/DiffHelper.php',
   'Simple_History\Vendor\Jfcherng\Diff\Differ' => $strauss_src . '/jfcherng/php-diff/src/Differ.php',
   'Simple_History\Vendor\Jfcherng\Diff\Exception\UnsupportedFunctionException' => $strauss_src . '/jfcherng/php-diff/src/Exception/UnsupportedFunctionException.php',
   'Simple_History\Vendor\Jfcherng\Diff\Exception\FileNotFoundException' => $strauss_src . '/jfcherng/php-diff/src/Exception/FileNotFoundException.php',
   'Simple_History\Vendor\Jfcherng\Diff\Factory\LineRendererFactory' => $strauss_src . '/jfcherng/php-diff/src/Factory/LineRendererFactory.php',
   'Simple_History\Vendor\Jfcherng\Diff\Factory\RendererFactory' => $strauss_src . '/jfcherng/php-diff/src/Factory/RendererFactory.php',
   'Simple_History\Vendor\Jfcherng\Diff\Utility\Str' => $strauss_src . '/jfcherng/php-diff/src/Utility/Str.php',
   'Simple_History\Vendor\Jfcherng\Diff\Utility\ReverseIterator' => $strauss_src . '/jfcherng/php-diff/src/Utility/ReverseIterator.php',
   'Simple_History\Vendor\Jfcherng\Diff\Utility\Language' => $strauss_src . '/jfcherng/php-diff/src/Utility/Language.php',
   'Simple_History\Vendor\Jfcherng\Diff\Utility\Arr' => $strauss_src . '/jfcherng/php-diff/src/Utility/Arr.php',
   'Simple_History\Vendor\Jfcherng\Utility\CliColor' => $strauss_src . '/jfcherng/php-color-output/src/CliColor.php',
);