<?php
/**
 * Template for weekly emails.
 */

defined( 'ABSPATH' ) || exit;

$site_name = get_bloginfo( 'name' );
$site_url = get_bloginfo( 'url' );
$date_range = sprintf(
	/* translators: 1: start date, 2: end date */
	__( '%1$s to %2$s', 'simple-history' ),
	date_i18n( get_option( 'date_format' ), strtotime( '-7 days' ) ),
	date_i18n( get_option( 'date_format' ), time() )
);
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title><?php esc_html_e( 'Weekly Website Statistics Report', 'simple-history' ); ?></title>
	<style>
		body {
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			line-height: 1.6;
			color: #333;
			max-width: 800px;
			margin: 0 auto;
			padding: 20px;
		}
	</style>
</head>
<body>
	<div class="header">
		<h1><?php echo esc_html( $site_name ); ?></h1>
		<h2><?php esc_html_e( 'Weekly Website Statistics Report', 'simple-history' ); ?></h2>
		<p><?php echo esc_html( $date_range ); ?></p>
	</div>

	<div class="footer">
		<p>
			<?php
			printf(
				/* translators: 1: site name, 2: site URL */
				esc_html__( 'This report was automatically generated by %1$s. Visit %2$s to view more detailed statistics.', 'simple-history' ),
				'<a href="' . esc_url( $site_url ) . '">' . esc_html( $site_name ) . '</a>',
				'<a href="' . esc_url( admin_url( 'admin.php?page=simple_history_page' ) ) . '">' . esc_html__( 'Simple History', 'simple-history' ) . '</a>'
			);
			?>
		</p>
	</div>
</body>
</html>
